
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package fnplot.syntax;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MOD = 8;
  public static final int PLOT = 23;
  public static final int MAPSTO = 21;
  public static final int PLUS = 4;
  public static final int RBRACE = 13;
  public static final int RPAREN = 3;
  public static final int SEMI = 15;
  public static final int IN = 11;
  public static final int CLEAR = 20;
  public static final int VARIABLE = 25;
  public static final int COLON = 18;
  public static final int LPAREN = 2;
  public static final int LBRACE = 12;
  public static final int COMMA = 14;
  public static final int EOF = 0;
  public static final int DIV = 7;
  public static final int MINUS = 5;
  public static final int error = 1;
  public static final int LET = 10;
  public static final int ASSIGN = 9;
  public static final int INTEGER = 24;
  public static final int FOR = 22;
  public static final int REAL = 26;
  public static final int LSBRACE = 16;
  public static final int MUL = 6;
  public static final int RSBRACE = 17;
  public static final int FUN = 19;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LPAREN",
  "RPAREN",
  "PLUS",
  "MINUS",
  "MUL",
  "DIV",
  "MOD",
  "ASSIGN",
  "LET",
  "IN",
  "LBRACE",
  "RBRACE",
  "COMMA",
  "SEMI",
  "LSBRACE",
  "RSBRACE",
  "COLON",
  "FUN",
  "CLEAR",
  "MAPSTO",
  "FOR",
  "PLOT",
  "INTEGER",
  "VARIABLE",
  "REAL"
  };
}

